name: Bug
description: Fixes a known bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: Include details and be descriptive
      placeholder: This bug ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A concise description of what you expected to happen.
      placeholder: The expected behavior is ...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: List the steps to reproduce
      description: Include details and be descriptive
      placeholder: |
        - [ ] Task One
        - [ ] Task Two
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment is this?
      options:
        - Production
        - Staging
        - Development
        - All
      default: 0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: Anything else?
      description: Links? References? Anything that will give us more context about the bug!
      placeholder: |
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false