name: Chore
description: General cleanup and maintenance
title: "[Chore]: "
labels: ["chore"]
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe the chore
      description: Include details and be descriptive
      placeholder: This chore...
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: List the tasks to be completed
      description: Include details and be descriptive
      placeholder: |
        - [ ] Task One
        - [ ] Task Two
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why is this chore being done?
      description: A concise description of what this chore will achieve.
      placeholder: This chore is being done to ...
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Anything else?
      description: Links? References? Anything that will give us more context about the chore!
      placeholder: |
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false