name: CI/CD
description: Continuous integration and continuous delivery
title: "[CI/CD]: "
labels: ["ci/cd"]
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe the CI/CD changes
      description: Include details and be descriptive
      placeholder: This will...
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment is this?
      options:
        - Production
        - Staging
        - Development
        - All
      default: 0
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: List the tasks to be completed
      description: Include details and be descriptive
      placeholder: |
        - [ ] Task One
        - [ ] Task Two
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A concise description of what you expect to happen.
      placeholder: The expected behavior is ...
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Anything else?
      description: Links? References? Anything that will give us more context about the ci/cd!
      placeholder: |
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false