name: Docs
description: Improvements or additions to documentation
title: "[Docs]: "
labels: ["docs"]
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe the documentation changes
      description: Include details and be descriptive
      placeholder: This documentation will...
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Anything else?
      description: Links? References? Anything that will give us more context about the docs!
      placeholder: |
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false