name: Feature
description: A new feature to the system
title: "[Feature]: "
labels: ["feature"]
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe the feature
      description: Include details and be descriptive
      placeholder: This feature...
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: List the tasks to be completed
      description: Include details and be descriptive
      placeholder: |
        - [ ] Task One
        - [ ] Task Two
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why is this feature being done?
      description: A concise description of what this feature will achieve.
      placeholder: This feature is being added to ...
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Anything else?
      description: Links? References? Anything that will give us more context about the feature!
      placeholder: |
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false