name: Refactor
description: Restructuring existing code without changing its behavior
title: "[Refactor]: "
labels: ["refactor"]
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe the refactor
      description: Include details and be descriptive
      placeholder: This refactor...
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: List the tasks to be completed
      description: Include details and be descriptive
      placeholder: |
        - [ ] Task One
        - [ ] Task Two
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why is this refactor being done?
      description: A concise description of what this refactor will achieve.
      placeholder: This refactor will allow ...
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Anything else?
      description: Links? References? Anything that will give us more context about the refactor!
      placeholder: |
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false