name: Test
description: Implementing new tests
title: "[Test]: "
labels: ["test"]
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe the testing
      description: Include details and be descriptive
      placeholder: These tests will...
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Test type
      description: What kind of tests are these?
      options:
        - Unit
        - Integration
        - Functional
        - End-To-End
        - Performance
      default: 0
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: List what these tests will cover
      description: Include details and be descriptive
      placeholder: |
        - [ ] Task One
        - [ ] Task Two
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Anything else?
      description: Links? References? Anything that will give us more context about the tests!
      placeholder: |
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false